### ISSUE TITLE
Google Drive / G Suite extension for Potplayer?

### ISSUE THREAD

**Issue by thelastfantasy** [TwitchPotPlayer/TwitchPotPlayer#2]
It seems the official Youtube extension does not support Google Drive / G Suite urls even they have the similar API.
Some url examples:
https://drive.google.com/file/d/1sKuCUPKUeEn2e7wiIC57WllPrAGBenJ9mQ/view?usp=sharing
https://drive.google.com/open?id=1sKuCUPKUeEn2e7wiIC57WllPrAGBenJ9mQ

**Comment by 23rd** [comment]
I'm not sure I want to develop something that requires a connection with the Google.
Sorry.
