### ISSUE TITLE
oauthToken doesn't allow me to watch subscriber only content

### ISSUE THREAD

**Issue by BeeJayJayn** [TwitchPotPlayer/TwitchPotPlayer#28]
I have created an app, set `useOwnCredentials=1` , got my `ClientID` and `ClientSecret` and added an `oauthToken`.

I can't load sub-only videos, and normal videos aren't able to load as soon as I add the `oauthToken`. Either the instructions are unclear or I'm missing a step that is not existing in any of the documentations. 

Error:

Failed to start playback.

Unable to connect to the requested server;
-Check that the URL is correct and the server is running
-Check the you're connrected to the net and PP isn't blocked by a firewall

This always comes for the sub-only video, but only for the free to watch one when i enter the `oauthToken`. 

sub only: https://www.twitch.tv/videos/892168013 - Critical Role
free vod: https://www.twitch.tv/videos/839812016 - MonsterCat

**Comment by BeeJayJayn** [comment]
On top I only get two of my several channels im following shown after setting up `twitchLogin`

**Comment by 23rd** [comment]
You can use your `oauthToken` without the `useOwnCredentials` field.

**Comment by BinToss** [comment]
Did you set the `twitchLogin=` field, too? I've discovered subscriber-only features like ad-free viewing only worked when `twitchLogin` was filled in addition to `clientID` and `clientSecret`.
